version: "3"

volumes:
  dev_database_data:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: droplet
    ports:
     - "3001:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "3002:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: droplet
      ME_CONFIG_MONGODB_URL: mongodb://root:droplet@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo

  mail:
    image: mailhog/mailhog
    ports:
      - "3003:1025"
      - "3004:8025"