version: "3"

services:
  database:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_AUTH_USER
      - MYSQL_PASSWORD=$DB_AUTH_PASS
      - MYSQL_ROOT_PASSWORD=$DB_AUTH_PASS
      - MYSQL_ROOT_HOST=$DB_ROOT_HOST
    ports:
      - "3306:3306"
    volumes:
      - $DB_DATA_LOCATION:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui