name: Deploy To Stage

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
    - run: yarn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v1.0.0
      env:
        DB_NAME: ${{ secrets.DB_STAGE_NAME }}
        DB_AUTH_USER: ${{ secrets.DB_STAGE_AUTH_USER }}
        DB_AUTH_PASS: ${{ secrets.DB_STAGE_AUTH_PASS }}
        DB_ROOT_HOST: ${{ secrets.DB_STAGE_ROOT_HOST }}
        EMAIL_HOST: ${{ secrets.EMAIL_STAGE_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_STAGE_PORT }}
        EMAIL_SECURE: ${{ secrets.EMAIL_STAGE_SECURE }}
        EMAIL_FROM_NAME: ${{ secrets.EMAIL_STAGE_FROM_NAME }}
        EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_STAGE_FROM_ADDRESS }}
        EMAIL_AUTH_ENABLE: ${{ secrets.EMAIL_STAGE_AUTH_ENABLE }}
        EMAIL_AUTH_USER: ${{ secrets.EMAIL_STAGE_AUTH_USER }}
        EMAIL_AUTH_PASS: ${{ secrets.EMAIL_STAGE_AUTH_PASS }}
        EMAIL_TLS_REJECT_UNAUTHORISED: ${{ secrets.EMAIL_STAGE_TLS_REJECT_UNAUTHORISED }}
        EMAIL_TEMPLATE_PASSWORDRESET_RESETLINK: ${{ vars.EMAIL_STAGE_TEMPLATE_PASSWORDRESET_RESETLINK }}
        EMAIL_TEMPLATE_VERIFYUSER_VERIFYLINK: ${{ vars.EMAIL_STAGE_TEMPLATE_VERIFYUSER_VERIFYLINK }}
      with:
        host: ${{ secrets.SSH_STAGE_HOST }}
        username: ${{ secrets.SSH_STAGE_USER }}
        key: ${{ secrets.SSH_STAGE_KEY }}
        port: ${{ secrets.SSH_STAGE_PORT }}
        script: ${{ secrets.SSH_STAGE_COMMAND }}
        envs: DB_NAME,DB_AUTH_USER,DB_AUTH_PASS,DB_ROOT_HOST,EMAIL_HOST,EMAIL_PORT,EMAIL_SECURE,EMAIL_FROM_NAME,EMAIL_FROM_ADDRESS,EMAIL_AUTH_ENABLE,EMAIL_AUTH_USER,EMAIL_AUTH_PASS,EMAIL_TLS_REJECT_UNAUTHORISED,EMAIL_TEMPLATE_PASSWORDRESET_RESETLINK,EMAIL_TEMPLATE_VERIFYUSER_VERIFYLINK

