name: staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Test
      - run: yarn test
      - name: Deploy Staging
        uses: D3rHase/ssh-command-action@{version}
        with:
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USER}}
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
          COMMAND: ${{secrets.STAGE_COMMAND}}